# Generated by Django 5.2.1 on 2025-11-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Versão 'amigável' do nome para URLs. Ex: acervo-artistico", unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Dificuldade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Fácil (3x3), Médio (4x4)', max_length=50, unique=True)),
                ('tamanho_cartela', models.IntegerField(default=3, help_text='O lado da cartela (N para NxN). Mínimo 2.')),
            ],
            options={
                'verbose_name_plural': 'Dificuldades',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.CharField(help_text='Esta é a palavra/frase que aparecerá na cartela.', max_length=150, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='meu_app.categoria')),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
                'ordering': ['categoria', 'resposta'],
            },
        ),
    ]
