# Generated by Django 5.2.1 on 2025-11-13 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_parte', models.CharField(choices=[('CABECA', 'Cabeça/Cabelo'), ('OLHOS', 'Olhos'), ('NARIZ', 'Nariz'), ('BOCA', 'Boca'), ('ROSTO', 'Rosto'), ('PAISAGEM', 'Paisagem')], max_length=10)),
                ('obra_original', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='partes_cabecas/')),
            ],
        ),
        migrations.CreateModel(
            name='MontagemUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_montagem', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprovada', models.BooleanField(default=False)),
                ('boca_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_boca', to='meu_app.obraparte')),
                ('cabeca_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_cabeca', to='meu_app.obraparte')),
                ('nariz_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_nariz', to='meu_app.obraparte')),
                ('olhos_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_olhos', to='meu_app.obraparte')),
            ],
        ),
    ]
