# Generated by Django 5.2.1 on 2025-11-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_obraparte_montagemusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montagemusuario',
            options={'verbose_name': 'Montagem do Usuário', 'verbose_name_plural': 'Montagens dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='obraparte',
            options={'verbose_name': 'Parte da Obra', 'verbose_name_plural': 'Partes das Obras'},
        ),
        migrations.AddField(
            model_name='montagemusuario',
            name='paisagem_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montagens_paisagem', to='meu_app.obraparte', verbose_name='Paisagem'),
        ),
        migrations.AlterField(
            model_name='montagemusuario',
            name='boca_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_boca', to='meu_app.obraparte', verbose_name='Boca'),
        ),
        migrations.AlterField(
            model_name='montagemusuario',
            name='cabeca_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_cabeca', to='meu_app.obraparte', verbose_name='Cabeça/Base'),
        ),
        migrations.AlterField(
            model_name='montagemusuario',
            name='nariz_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_nariz', to='meu_app.obraparte', verbose_name='Nariz'),
        ),
        migrations.AlterField(
            model_name='montagemusuario',
            name='olhos_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montagens_olhos', to='meu_app.obraparte', verbose_name='Olhos'),
        ),
        migrations.AlterField(
            model_name='obraparte',
            name='tipo_parte',
            field=models.CharField(choices=[('CABECA', 'Cabeça/Cabelo'), ('OLHOS', 'Olhos'), ('NARIZ', 'Nariz'), ('BOCA', 'Boca'), ('PAISAGEM', 'Paisagem')], max_length=10),
        ),
    ]
