# Generated by Django 5.2.1 on 2025-11-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_alter_montagemusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaCacaPalavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(help_text='Breve descrição do tema para a tela de seleção.')),
            ],
        ),
        migrations.CreateModel(
            name='PalavraCacaPalavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(help_text='A palavra EXATA a ser procurada na grade (em MAIÚSCULAS).', max_length=50)),
                ('descricao', models.TextField(help_text='Descrição ou dica sobre a palavra (exibida ao lado da lista).')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras', to='meu_app.temacacapalavras')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCacaPalavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.IntegerField(default=12)),
                ('layout_json', models.JSONField(blank=True, null=True)),
                ('tema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='meu_app.temacacapalavras')),
            ],
        ),
    ]
