# Generated by Django 5.2.1 on 2025-11-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_temacacapalavras_palavracacapalavras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DificuldadeMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Fácil, Médio, Difícil.', max_length=50, unique=True)),
                ('num_colunas', models.IntegerField(default=4, help_text='Número de colunas do tabuleiro.')),
                ('num_linhas', models.IntegerField(default=4, help_text='Número de linhas do tabuleiro.')),
            ],
            options={
                'verbose_name_plural': 'Dificuldades da Memória',
                'ordering': ['num_linhas', 'num_colunas'],
            },
        ),
        migrations.CreateModel(
            name='TemaMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição breve para a tela de seleção.')),
            ],
            options={
                'verbose_name_plural': 'Temas da Memória',
            },
        ),
        migrations.CreateModel(
            name='CartaMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='memoria/pares/', verbose_name='Frente da Carta')),
                ('par_id', models.CharField(help_text='Identificador Único para este par (Ex: MONALISA).', max_length=100)),
                ('verso_padrao', models.ImageField(help_text='Imagem usada como verso (contraparte) para todas as cartas do tema.', upload_to='memoria/versos/')),
                ('informacao_acerto', models.TextField(help_text='Texto ou curiosidade a ser exibido em um modal quando o par for acertado.')),
                ('tema', models.ForeignKey(help_text='Selecione o tema ao qual esta carta pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='meu_app.temamemoria')),
            ],
            options={
                'verbose_name_plural': 'Cartas da Memória',
                'unique_together': {('tema', 'par_id')},
            },
        ),
    ]
