# Generated by Django 5.2.1 on 2025-11-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0005_dificuldadememoria_temamemoria_cartamemoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartamemoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='memoria/pares/', verbose_name='Frente da Carta'),
        ),
        migrations.AlterField(
            model_name='cartamemoria',
            name='verso_padrao',
            field=models.ImageField(blank=True, help_text='Imagem usada como verso para todas as cartas do tema.', null=True, upload_to='memoria/versos/', verbose_name='Verso da Carta'),
        ),
    ]
