# Generated by Django 5.2.1 on 2025-11-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0006_alter_cartamemoria_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='quiz_pinturas/')),
            ],
            options={
                'verbose_name': 'Quiz Pintura',
                'verbose_name_plural': 'Quiz Pinturas',
            },
        ),
        migrations.CreateModel(
            name='QuizTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Quiz Tema',
                'verbose_name_plural': 'Quiz Temas',
            },
        ),
        migrations.CreateModel(
            name='QuizPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(default='Quem é o artista desta obra?', help_text='Exemplo: Quem pintou esta obra de arte?', max_length=500)),
                ('opcoes_incorretas', models.ManyToManyField(limit_choices_to={'id__gt': 0}, related_name='opcoes_incorretas_em_perguntas', to='meu_app.quizpintura')),
                ('pintura_pergunta', models.ForeignKey(help_text='A Pintura que será exibida para o usuário identificar.', on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_associadas', to='meu_app.quizpintura')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='meu_app.quiztema')),
            ],
            options={
                'verbose_name': 'Quiz Pergunta',
                'verbose_name_plural': 'Quiz Perguntas',
            },
        ),
    ]
